In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Create Two numpy array of size 3 X 2 and 2 X 3
#And randomly initialize them
nparr1 = np.random.randint(1,100,size=(3,2))
nparr2 = np.random.randint(1,100,size=(2,3))
print(nparr1)
print(nparr2)

[[17 82]
 [69 29]
 [90 69]]
[[28 83 51]
 [95 87 81]]


In [ ]:
#perform matrix multiplication
res = np.dot(nparr1,nparr2)
print(res)

[[ 8266  8545  7509]
 [ 4687  8250  5868]
 [ 9075 13473 10179]]


In [ ]:
#perform elementwise matrix multiplication
nparr3 = np.array([[1,2,3],[4,5,6]])
nparr4 = np.array([[4,5,6],[1,2,3]])

element_wise = nparr3 * nparr4
print(element_wise)

[[ 4 10 18]
 [ 4 10 18]]


In [ ]:
#Find mean of first matrix
mean = np.mean(nparr1)
print(mean)


59.333333333333336


In [ ]:
#Convert Numeric entries(columns) of mtcars.csv to their mean centered version
main_data = pd.read_csv("mtcars.csv")
del main_data['model']

# shwing the meancenter
mean_center = main_data.apply(lambda e: e - e.mean())
print(mean_center)

          mpg     cyl        disp        hp  ...      vs       am    gear    carb
0    0.909375 -0.1875  -70.721875  -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1    0.909375 -0.1875  -70.721875  -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2    2.709375 -2.1875 -122.721875  -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3    1.309375 -0.1875   27.278125  -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4   -1.390625  1.8125  129.278125   28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125
5   -1.990625 -0.1875   -5.721875  -41.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
6   -5.790625  1.8125  129.278125   98.3125  ... -0.4375 -0.40625 -0.6875  1.1875
7    4.309375 -2.1875  -84.021875  -84.6875  ...  0.5625 -0.40625  0.3125 -0.8125
8    2.709375 -2.1875  -89.921875  -51.6875  ...  0.5625 -0.40625  0.3125 -0.8125
9   -0.890625 -0.1875  -63.121875  -23.6875  ...  0.5625 -0.40625  0.3125  1.1875
10  -2.290625 -0.1875  -63.121875  -23.6875  ...  0.5625 -0.40625  0.3125  1.1875
11  -3.690625  1